from enum import Enum, auto

class EnemyType(Enum) :
    GOBLIN = auto()
    BANDIT = auto()
    NECROMANCER = auto()
    SKELETON = auto()
    SPIDER_LEGGED_CLOWN = auto()
    HUMAN_EATING_CATFISH = auto()
    SPIDERS_COLECTOR = auto()
    UNSUSPICIOUS_MUSTACHEMAN = auto()
    MYSTERIOUS_EGG = auto()
    DISHONEST_GOLEM = auto()
    CLOCKWORK_SHOVELGUY = auto()
    HYBRID_OF_A_HUMAN_AND_CENTIPEDE = auto()
    BULLSEYESNAKEFISH = auto()
    FIRE_ELEMENTAL = auto()
    WASP = auto()
    SWAMPMADE_HUMANOID = auto()
    SPIDERS_COLLLECTOR = auto()
    DUAL_HEADED_LIZARDMAN_BANDIT = auto()
    TOMATOHEAD = auto()
    UNSUCCESFUL_TRADER = auto()
    COYOTELIKE_SOMETHING = auto()
    ETHERNAL_LYNX = auto()
    EPHEMERAL_PYTHON = auto()
    HEADLESS_FIREFOX = auto()
